apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: changelog-github
  description: |
    <DESCRIPTION>
  tags:
    - camp-developer-experience
    - data-none
    - users-na
  annotations:
    github.com/project-slug: changelog-github
    github.com/team-slug: cultureamp/developer-experience
spec:
  type: library
  owner: developer-experience
  lifecycle: development
